### ISSUE TITLE
code climate integration messed up

### ISSUE THREAD

**Issue by bradfordcondon** [NAL-i5K/tripal_eutils#120]
<img width="1243" alt="screen shot 2019-01-15 at 1 19 47 pm" src="https://user-images.githubusercontent.com/7063154/51200712-4912b780-18c8-11e9-8120-bb9c31e89c74.png">
as you can see the sniffing/reading of the code isnt right.  i think the code coverage reporting is still correct.

**Comment by bradfordcondon** [comment]
I think this is from the  custom code climate config file not specifying hte maintainability tests should be added.

it says they are enabled by default, but lets try enabling everything:  

```
checks:
  argument-count:
    enabled: true
  complex-logic:
    enabled: true
  file-lines:
    enabled: true
  method-complexity:
    enabled: true
  method-count:
    enabled: true
  method-lines:
    enabled: true
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: true
  similar-code:
    enabled: true
  identical-code:
    enabled: true
```
